# Exception Handling in Python

This repository contains a comprehensive collection of codes and explanations related to the concept of exception handling 
in Python.

## Table of Contents

- [Introduction](#introduction)
- [Exception Handling Blocks](#exception-handling-blocks)
- [Usage](#usage)
- [Contributing](#contributing)

## Introduction

Exception handling is a crucial aspect of writing robust and reliable Python programs. It allows you to gracefully 
handle unexpected errors and exceptions that can occur during program execution. In this repository, we delve into 
the different components of exception handling in Python, including the `try`, `except`, `else`, and `finally` blocks
and various combinations of this.

## Exception Handling Blocks

We cover a wide range of topics related to exception handling, including:

- Using the `try` and `except` blocks to catch and handle specific exceptions.
- Employing the `else` block to execute code only if no exceptions occur.
- Leveraging the `finally` block for cleanup tasks that should run regardless of exceptions.
- Exploring various combinations of these blocks to create robust exception handling structures.

## Usage

Each subdirectory within this repository contains Python scripts that demonstrate different scenarios involving exception handling. To run these examples and understand how exception handling works, follow these steps:

1. Clone the repository:
   ```bash
   git clone https://github.com/kapil-malviya/exception-handeling.git
   ```

2. Navigate to the desired subdirectory:
   ```bash
   cd exception-handeling-in-python/
   ```

3. Run the Python script:
   ```bash
   python3 exception-13-nested-controlflow.py
   ```

Feel free to experiment with the provided code to gain a deeper understanding of exception handling in Python.

## Contributing

Contributions to this repository are welcome! If you'd like to add more examples, improve existing ones, or fix issues, 
please open a pull request. 

---
